server:
  port: 8080
  servlet:
    context-path: /travel
spring:
  resources:
    static-locations: file:D:\Upload
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  jpa:
    database: mysql
    show-sql: false
spring.servlet.multipart.max-file-size: 1024MB
spring.servlet.multipart.max-request-size: 1024MB
upload.path: D:\Upload