server:
  port: 1234
  servlet:
    context-path: /test
spring:
  resources:
    static-locations: file:D:\Upload
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
  jpa:
    database: mysql
    show-sql: true
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
upload.path: D:\Upload